document.write("<div id=\"Logo\" style=\"width:40%;height:120px;float:left;text-align:center;\">");
document.write("<div style=\"width:100%;height:50px;line-height:50px;font-size:32px;\">欧老师工作室</div>");
document.write("<div style=\"width:100%;height:30px;line-height:30px;font-size:12px;color:gray;\">教育的根是苦的,但其果是甜的</div>");
document.write("</div>");
document.write("<div id=\"BadgeHUST\" style=\"height:100px;line-height:100px;padding:0 10px 0 10px;text-align:center;float:right;\">");
document.write("<img src=\"Images/hust.png\" height=\"100px\">");
document.write("</div>");
document.write("<div id=\"BadgeYNOU\" style=\"height:100px;line-height:100px;padding:0 10px 0 10px;text-align:center;float:right;\">");
document.write("<img src=\"Images/ynou.png\" height=\"100px\">");
document.write("</div>");
document.write("<div id=\"BadgeYNU\" style=\"height:100px;line-height:100px;padding:0 10px 0 10px;text-align:center;float:right;\">");
document.write("<img src=\"Images/ynu.png\" height=\"100px\">");
document.write("</div>");