document.write("<div id=\"Logo\" style=\"width:40%;height:60px;float:left;text-align:center;\">");
document.write("<div style=\"width:100%;height:40px;line-height:40px;font-size:28px;\">欧老师工作室</div>");
document.write("<div style=\"width:100%;height:20px;line-height:20px;font-size:12px;color:gray;\">教育的根是苦的,但其果是甜的</div>");
document.write("</div>");
document.write("<div id=\"Navi\" style=\"width:60%;height:60px;float:left;\">");
document.write("<ul style=\"list-style:none;\">");
document.write("<li style=\"display:inline;padding:0 5px 0 5px;\"><a href=\"../index.html\" style=\"font-size:16px;font-family:Calibri;\">Home</a></li>");
document.write("<li style=\"display:inline;padding:0 5px 0 5px;\"><a href=\"../Course.html\" style=\"font-size:16px;font-family:Calibri;\">Course</a></li>");
document.write("<li style=\"display:inline;padding:0 5px 0 5px;\"><a href=\"../Publication.html\" style=\"font-size:16px;font-family:Calibri;\">Publication</a></li>");
document.write("<li style=\"display:inline;padding:0 5px 0 5px;\"><a href=\"../Project.html\" style=\"font-size:16px;font-family:Calibri;\">Project</a></li>");
document.write("<li style=\"display:inline;padding:0 5px 0 5px;\"><a href=\"../Award.html\" style=\"font-size:16px;font-family:Calibri;\">Award</a></li>");
document.write("<li style=\"display:inline;padding:0 5px 0 5px;\"><a href=\"../Miscellaneous.html\" style=\"font-size:16px;font-family:Calibri;\">Miscellaneous</a></li>");
document.write("<li style=\"display:inline;padding:0 5px 0 5px;\"><a href=\"../AboutMe.html\" style=\"font-size:16px;font-family:Calibri;\">AboutMe</a></li>");
document.write("</ul>");
document.write("</div>");