document.write("<div class=\"sidebar\">");
document.write("<h3>Latest</h3>");
document.write("<p><a href=\"../Blogs\\20140723001.html\">Caffe + Ubuntu 14.04 + CUDA 6.5 新手安装配置指南</a> <i style=\"color:gray;\">[2014-07-23]</i></p>");
document.write("<p><a href=\"../Blogs\\20140719001.html\">Caffe配置指南 on Windows8.1 + CUDA6.5 + VS2013 </a> <i style=\"color:gray;\">[2014-07-19]</i></p>");
document.write("<p><a href=\"../Blogs\\20140717001.html\">Cuda-convnet配置指南 on Windows8.1 + CUDA6.5 + VS2013</a> <i style=\"color:gray;\">[2014-07-17]</i></p>");
document.write("<h3>Contact</h3>");
document.write("<ul>");
document.write("<li>E—Mail：shiorioxy@qq.com</li>");
document.write("<li style=\"text-indent:52px;\">ouxinyu@hust.edu.cn</li>");
document.write("<li>QQ：14777591</li>");
document.write("<li>ScholarMate：<a href=\"http://www.scholarmate.com/profile/xinyuou1 \" target=\"_blank\"> 欧新宇（OuXinyu）</a></li>");
document.write("</ul>");
document.write("</div>");